name: Update Tag
description:
  This action reads a bump parameter along with other variables and fetches the
  latest tag, after which it increases the tag's version according with the
  parameters you pass
author: Maximiliano Diaz

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  bump:
    description:
      The type of bump to apply to the tag. Options can be major, minor, patch,
      premajor, preminor, prepatch prerelease or none. Defaults to none. Not
      required
    required: false
    default: 'none'
  prefix:
    description:
      The prefix to add to add to the tag and to include while searching for
      tags. Defaults to 'v'. Not required
    required: false
    default: 'v'
  suffix:
    description:
      The suffix to add to add to the tag and to include while searching for
      tags. Defaults to null/empty string. Not required
    required: false
    default: ''
  replace_suffix:
    description:
      Flag that marks whether a target suffix should be provided as the version
      is changing stage. Eg from v1.2.3-beta to v1.2.3 or from v1.2.0-rc.4 to
      v1.2.0
    required: false
    default: 'false'
  new_suffix:
    description:
      The target suffix to assign to the tag in place of the source one. Eg
      alpha -> beta or beta -> ''
    required: false
    default: 'undefined'
  github_token:
    description: 'Token to access GitHub.'
    required: true

# Define your outputs here.
outputs:
  updated_tag:
    description: The update tag version created from the parameters passed

runs:
  using: node24
  main: dist/index.js
